name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Create artifact (include dotfiles)
        run: |
          tar \
            --dereference --hard-dereference \
            --exclude=.git \
            --exclude=.github \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
